### ISSUE TITLE
Allow creating streamables by indicating directly an image URL

### ISSUE THREAD

**Issue by dfernandezm** [GraffiTab/GraffiTab-Backend#138]
Instead of uploading an image file, allow posting a URL that represents an image that would be returned directly when GETing the streamable.

* Change JSON for POST/PUT endpoint
* Create an Asset that just stores the `url`
* Shortcut mapping of AssetDto / Asset if there is `url` non-null field

**Comment by 8masterofpuppets8** [comment]
A small related change request. Currently in the `search/location` endpoint the API returns locations with coordinates 0.0/0.0, which is wrong because users might have chosen not to have locations attached to the posts.

We should add a filter to the HQL query which searches for locations within an area which checks if their values are != 0.0. NOTE: valid GPS coordinates can be <0 or >0, so I think we can filter them by comparing != 0.0.
