### ISSUE TITLE
Create CloudFront distribution pointing to PROD website 

### ISSUE THREAD

**Issue by dfernandezm** [GraffiTab/GraffiTab-Backend#181]
Same steps as DEV website pointed out in #122

**Comment by 8masterofpuppets8** [comment]
This is now configured and working for https://dev.graffitab.com, https://www.graffitab.com and https://graffitab.com. 

The steps to create the S3 static host distribution for `graffitab.com` are the same as dev above.

However, the configuration for the main domain could not be done without changing the nameserver configuration for GoDaddy to point to Route 53 and duplicating our zone information in Route 53. Here are the steps that had to be done:

- [ ] Export zone information from GoDaddy.
- [ ] Create new hosted zone on Route 53 called `graffitab.com`. This zone is now the root of everything, including all subdomains etc.
- [ ] Remove existing zones in Route 53 `dev.graffitab.com` and `website.graffitab.com`. These are no longer needed as the subdomains will be configured in the `graffitab.com` global zone.
- [ ] Import the zone file from GoDaddy into our new `graffitam.com` zone in Route 53.
- [ ] **Note:** make sure to check the values that AWS creates after the import - it appends incorrect `.graffitab.com` content in the end if the value is a Url rather than an IP address.
- [ ] Take note of the name server (NS) values generated by AWS and replace the default GoDaddy NS values with them. **Note:** they all have to be replaced at which point GoDaddy will stop showing zone information and say that the zone info is provided somewhere else.
- [ ] After the DNS has propagated (a few hours locally) the main website and dev website should point to CloudFront correctly. **Note:** also make sure to check the other redirections and subdomains such as dev01, dev02, devlb, prd01, prd02, prdlb, the databases and email servers.

After all this is done we have to redirect https://www.graffitab.com to the main website Here are steps to do this:
- [ ] In S3 create a new bucket `www.graffitab.com` which is empty.
- [ ] Enable static website hosting but redirect all traffic to `graffitab.com` with HTTPS.
- [ ] Make sure bucket has public access for `GET` requests.
- [ ] Create CloudFront distribution for this bucket and make sure it deploys properly. **Note:** when creating the CloudFront distribution use the public url of the bucket rather than the REST url suggested by CloudFront with autocomplete. **CloudFront only allows this redirection with the public bucket url, not with the REST endpoint.**
- [ ] Create a `CNAME` in Route 53 aliasing to the new CloudFront distribution.
- [ ] After the DNS propagates verify that https://www.graffitab.com works properly.
